version: '1'

services:
  db:
    image: postgres:latest
    container_name: goblog-db
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    ports:
      - ${DB_PORT}:${DB_PORT}
    healthcheck:
      test: "pg_isready -h db -p 5432 -U ${DB_USER}"
      interval: 1s
      timeout: 60s
      retries: 60
    volumes:
      - ./goblog-db.sql:/docker-entrypoint-initdb.d/init.sql

  main-app:
    build:
      context: .
    container_name: goblog-app
    env_file:
      - .env
    environment:
      - DB_HOST=db
    ports:
      - ${HTTP_PORT}:${HTTP_PORT}
    depends_on:
      db:
        condition: service_healthy
